server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}

spring:
  application:
    name: RESTAURANT-SERVICE
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    # profiles:
    #   active: default
logging:
  level:
    root: INFO
    com.shikbeTumio.restaurantlisting: DEBUG
    org.springframework.web: ERROR
